on: pull_request
name: Build and Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [ 1.22.x ]
        platform: [ ubuntu-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Test
        run: |
          go run github.com/onsi/ginkgo/v2/ginkgo --race -r ./...
      - name: Build
        run: make build
  test-git:
    strategy:
      matrix:
        go-version: [1.22.x]
        platform: [ubuntu-latest]
        tags: [
          "gitbinary",
          "nogit",
          "none",      # Arbitrary tag used to exercise the default git build (no special git tag)
        ]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Test
      run: |
        go run github.com/onsi/ginkgo/v2/ginkgo -tags ${{ matrix.tags }} --race -r ./...